### ISSUE TITLE
Unable to build on Raspberry Pi 3 / Raspbian - error: ‘EAX’ undeclared

### ISSUE THREAD

**Issue by joolswills** [mupen64plus/mupen64plus-core#517] opened 2018-01-13 15:50 UTC
Looks like it could be related to recent dynarec changes. https://github.com/mupen64plus/mupen64plus-core/pull/515 looks related too.

Building on Raspbian Jessie (current git HEAD - 865a184527e453197547625488d1e744e4426377)

```
make -C mupen64plus-core/projects/unix all VC=1 NEON=1 'OPTFLAGS=-O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -O3 -flto

...

../../src/device/r4300/new_dynarec/new_dynarec.c: In function ‘syscall_assemble’:
../../src/device/r4300/new_dynarec/new_dynarec.c:4732:25: error: ‘EAX’ undeclared (first use in this function)
   emit_movimm(start+i*4,EAX); // Get PC
                         ^
../../src/device/r4300/new_dynarec/new_dynarec.c:4732:25: note: each undeclared identifier is reported only once for each function it appears in
../../src/device/r4300/new_dynarec/new_dynarec.c:4729:15: warning: unused variable ‘ccreg’ [-Wunused-variable]
   signed char ccreg=get_reg(i_regs->regmap,CCREG);
               ^
../../src/device/r4300/new_dynarec/new_dynarec.c: In function ‘do_ccstub’:
../../src/device/r4300/new_dynarec/new_dynarec.c:5745:29: error: ‘EAX’ undeclared (first use in this function)
     emit_movimm(stubs[n][5],EAX);
                             ^
../../src/device/r4300/new_dynarec/new_dynarec.c: In function ‘rjump_assemble’:
../../src/device/r4300/new_dynarec/new_dynarec.c:6088:10: warning: variable ‘cc’ set but not used [-Wunused-but-set-variable]
   int rs,cc;
          ^
../../src/device/r4300/new_dynarec/new_dynarec.c: At top level:
../../src/device/r4300/new_dynarec/new_dynarec.c:67:13: warning: ‘nullf’ defined but not used [-Wunused-function]
 static void nullf() {}
             ^
../../src/device/r4300/new_dynarec/new_dynarec.c:10935:17: warning: ‘ldl_merge’ defined but not used [-Wunused-function]
 static uint64_t ldl_merge(uint64_t original,uint64_t loaded,u_int bits)
                 ^
../../src/device/r4300/new_dynarec/new_dynarec.c:10946:17: warning: ‘ldr_merge’ defined but not used [-Wunused-function]
 static uint64_t ldr_merge(uint64_t original,uint64_t loaded,u_int bits)
                 ^
In file included from ../../src/device/r4300/new_dynarec/new_dynarec.c:1678:0:
../../src/device/r4300/new_dynarec/arm/assem_arm.c:1011:13: warning: ‘regname’ defined but not used [-Wunused-variable]
 static char regname[16][4] = {
             ^
../../src/device/r4300/new_dynarec/arm/assem_arm.c:1029:13: warning: ‘output_byte’ defined but not used [-Wunused-function]
 static void output_byte(u_char byte)
             ^
../../src/device/r4300/new_dynarec/arm/assem_arm.c:1033:13: warning: ‘output_modrm’ defined but not used [-Wunused-function]
 static void output_modrm(u_char mod,u_char rm,u_char ext)
             ^
../../src/device/r4300/new_dynarec/arm/assem_arm.c:1187:13: warning: ‘emit_loadlp’ defined but not used [-Wunused-function]
 static void emit_loadlp(u_int imm,u_int rt)
             ^
../../src/device/r4300/new_dynarec/arm/assem_arm.c:1865:13: warning: ‘emit_pushreg’ defined but not used [-Wunused-function]
 static void emit_pushreg(u_int r)
             ^
../../src/device/r4300/new_dynarec/arm/assem_arm.c:1870:13: warning: ‘emit_popreg’ defined but not used [-Wunused-function]
 static void emit_popreg(u_int r)
             ^
../../src/device/r4300/new_dynarec/arm/assem_arm.c:2121:13: warning: ‘emit_writehword’ defined but not used [-Wunused-function]
 static void emit_writehword(int rt, int addr)
             ^
../../src/device/r4300/new_dynarec/new_dynarec.c:7493:13: warning: ‘disassemble_inst’ defined but not used [-Wunused-function]
 static void disassemble_inst(int i)
             ^
    CC  _obj/main/zip/unzip.o
Makefile:704: recipe for target '_obj/device/r4300/new_dynarec/new_dynarec.o' failed
make: *** [_obj/device/r4300/new_dynarec/new_dynarec.o] Error 1
```

**Comment by bsmiles32** [comment] 2018-01-13 15:53
Yeah, I broke compilation of the arm dynarec very recently, @fzurita reported it and I proposed PR #515 to fix it. If you can try this PR and confirm that it works, I'll merge it so master doesn't stay broken too long for ARM dynarec. Thanks

**Comment by joolswills** [comment] 2018-01-13 15:58
Yeah sorry - I saw that PR and misread it as already merged/closed. Sorry. will try.

**Comment by bsmiles32** [comment] 2018-01-13 16:07
try something like that in your mupen64plus directory :
git remote add bsmiles32 https://github.com/bsmiles32/mupen64plus-core
git fetch bsmiles32
git checkout bsmiles32/arm_compile_fix
cd project/unix
make clean && make DEBUG=1 all

**Comment by joolswills** [comment] 2018-01-13 16:09
thanks. I have it building now.

**Comment by bsmiles32** [comment] 2018-01-13 16:12
So you confirm that the PR is Ok and I can merge it to master ?

**Comment by joolswills** [comment] 2018-01-13 16:19
it builds thanks - I didn't test yet.

**Comment by joolswills** [comment] 2018-01-13 16:28
I'm getting a segmentation fault (testing with goldeneye), but may not be related as I get it with Pure Interpreter also). Feel free to merge, and I will bisect the crash.

**Comment by bsmiles32** [comment] 2018-01-13 17:06
Good. So I merged the compilation fix to master.
But I wasn't able to reproduce the crash on my end. I've played through the first level with no crash (pure_interpreter).

**Comment by fzurita** [comment] 2018-01-13 17:32
It's building ok now I'm Android. I don't get the GoldenEye crash.

**Comment by bsmiles32** [comment] 2018-01-13 17:37
@joolswills Make sure you start from a clean build, because some headers are generated a compile-time and may not be rebuild when some compilation flags changes.

make clean && make DEBUG=1 all

If after that you still get the crash, try to get a backtrace with gdb

gdb --args mupen64plus goldeneye.n64 (or whatever arguments you use)
> r
... when you reach the crash, enter in gdb command prompt
> bt
and paste the result here so we can see the backtrace

**Closed** 2021-06-24 15:41 UTC
