### ISSUE TITLE
Mario Kart 64 item not usable bug

### ISSUE THREAD

**Issue by MorganCreek** [mupen64plus/mupen64plus-core#245] opened 2017-02-25 09:23 UTC
Hey,
I've encountered a bug with items in multiplayer.
Randomly the item can not be used, so you are stuck with the item until the end of the race. This seems to happen exclusively in multiplayer. The controllers are properly configured.
Platform: Raspberry Pi 3, RetroPie 4.1
Emulators: mupen64plus based emulators to date (mupen64plus standalone, lr-mupen (the new one), lr-GlupeN64)(didn't test lr-paraLLEl)
Roms tested: Mario Kart 64 (Europe) (Rev A); Mario Kart 64 (E) (V1.1) [!]
Controller: Hiujia/Mayflash N64 to USB adapter, xboxdrv
Thread in RetroPie forum: https://retropie.org.uk/forum/topic/8132/mario-kart-64-item-issue/9

I don't know if this is the right place to post this issue, I already posted it here: https://github.com/mupen64plus/mupen64plus-user-issues/issues/686

**Comment by audetto** [comment] 2017-05-04 12:28
Got a similar issue.
for me the item is the continuous booster.
Originally I thought it had to do with controller mapping and turbo button, but I could not find a solution.

and I've only ever seen it in 2 player mode.

I run it in libretro on Linux with both Xbox and PS3 controllers.

**Comment by hoderer** [comment] 2017-05-13 20:05
I can confirm this issue. Happens to me on every rom I tried (latest mupen64 FZ from playstore). Also DKs Jungle Parkway is way too fast in 2 player mode. This is a known issue but it doesnt seem to be fixed yet. Any news on the item issue? Maybe there's a rom out there which works. I noticed different bugs on different roms. Does anyone know a solution for this? Since the 8bitdo N64 controller is out, it's finally somehow better than the original feeling when playing with an emulator and the wireless n64-pad.

**Comment by fzurita** [comment] 2017-05-13 20:35
I don't think I have the expertise to fix this kind of issue.  Although, there is a very crude workaround with Mupen64plus-fz. Open the sidebar while in game and adjust the game speed to 70%.

**Comment by hoderer** [comment] 2017-05-13 20:38
Thanks for your quick reply and for this 'funny' hint! It's quite strange, but at least there is some work around possible... So, let's hope for the future. I'll keep an eye on it... and thanks again! :-)

**Comment by 42Swampy** [comment] 2017-05-16 16:48
In older versions of mupen64plus the problem didn't exist. I don't know in which update it changed.
A year ago, I played it with my girlfriend with no problems.

Platform: Raspberry Pi 3, RetroPie 4.23

**Comment by loganmc10** [comment] 2017-05-16 17:18
The only thing I can think of that was specifically done for this game was this:

https://github.com/mupen64plus/mupen64plus-core/pull/203

Which was supposed to fix speed issues when playing multiplayer. It's possible it could mess with something else in the game.

Someone could test by reverting this commit/removing these lines:

https://github.com/mupen64plus/mupen64plus-core/pull/203/commits/3e93a38cbbf3d9ad292210a8e3114855bf96fa2c

**Comment by hoderer** [comment] 2017-05-16 21:37
@loganmc10: Thanks ALOT for investigating this! Looks like we really have something here, but I'm absolutely no programmer and don't have a clue how to revert changes and compile a new APK. If someone could do that, I would test it immidiately on my phone.

**Comment by fzurita** [comment] 2017-05-16 21:42
Those are ini settings. They can be edited it out with a text editor.

**Comment by hoderer** [comment] 2017-05-16 23:58
Thanks alot! I edited the INI and did some testing, but it's not that easy to test 2-player-mode when you're alone. So I drove just the first race of every cup. First impression: The "item not usable bug" seems to be gone. But I need more testing with "real" 2-players, which I do in the next days. For now I'm quite happy, but D.K.'s Jungle Parkway is too fast on every rom I tried. I'm not 100% sure, but - correct me if I'm wrong - I think one rom version was working before and didn't have this "too fast"-bug...

I tested the following roms:
Mario Kart 64 (E) (v1.0) (!)
Mario Kart 64 (E) (v1.1) (o1)
Mario Kart 64 (U) (!)
Mario Kart 64 (U) (o2)

I noticed also differences in widescreen. The E-Versions have borders up and down, the U-Versions are "real" fullscreen (probably some PAL & NTSC stuff or someting like that).

**Comment by hoderer** [comment] 2017-05-17 11:16
Did some more digging. It's interesting that D.K.'s Jungle Parkway is working with the old ini and the following roms:

Mario Kart 64 (U) [!]
Mario Kart 64 (U) [02]

Since I'm from germany I mostly played the the E-Versions, which are still too fast. I know that's not the item-problem, but I think that's also somehow related to the #203 changes. Maybe this is helpful for investigating.

**Comment by loganmc10** [comment] 2017-05-17 15:47
So I just tested this on my PC. I tested the US version of the ROM.

Without the cheat in the ini file, DK's Jungle Parkway is wayyy too fast. Other tracks seemed fine. With the cheat, the speed was correct.

You can read about the cheat here if you'd like:
http://tasvideos.org/GameResources/N64/MarioKart64/Patches.html

It's possible that the cheat only works with the US version of the ROM. Typically cheats have different versions for different regions, but this one didn't.

It's also possible that this cheat does mess with the items, but then you are left with a tricky situation. Do you remove the cheat and break DK's Jungle Parkway (and maybe other tracks, I didn't try them all), or do you leave it and break item drops?

There aren't many people with the skillset to diagnose a cheat like this, maybe @retrobenny

**Comment by loganmc10** [comment] 2017-05-17 16:18
First things first though, we need someone to verify that this cheat code is indeed what is causing the item usage issues. Project64 uses this same cheat, and I haven't seen anyone on their forums complain about this issue.

**Comment by loganmc10** [comment] 2017-05-17 16:22
The other possibility: Maybe the item usage issue is only happening on (E) roms? Both of you mentioned that you are using (E) roms. I think maybe this cheat was meant only for the (U) version of the ROM, so maybe this cheat is modifying the wrong thing with the (E) ROMs, and it just needs to be applied to the (U) ROM only.

**Comment by hoderer** [comment] 2017-05-17 16:25
Good point, but it's most likely the cheat code. I remember playing ALOT of mario kart before the cheat applied and never had any issues like that. To be sure and to (kind of) confirm, I play tonight without the cheat a little while. I believe it won't happen without the cheatcodes.

@loganmc10: just saw your post. It's definetely not happening only on E-roms. I tried U-roms 2 months ago for the first time and noticed the jungle parkway speed fix, but was disappointed that the item-bug was in there, too...

**Comment by loganmc10** [comment] 2017-05-17 16:27
At the very least we can probably remove the cheat for E and J versions of the ROM, since it only seems to work with the U rom? Is that right? At least then you'd have the option of using the E version if you want to avoid the item bug and the U version if you want the speed correct..

**Comment by hoderer** [comment] 2017-05-17 16:30
yes, that would be cool and it's a good start :-)

but I didn't test J-versions...

**Comment by loganmc10** [comment] 2017-05-17 16:34
Every other cheat seems to be region specific. Someone else could probably figure out what the values should be for E and J, but I'm not sure what that process involves.

**Comment by loganmc10** [comment] 2017-05-17 17:14
I updated the cheat code values for the E and J ROM's and submitted a PR:

https://github.com/mupen64plus/mupen64plus-core/pull/279

Now at least we will have the proper values for the cheat codes, I would suggest trying the ini file from that PR (https://raw.githubusercontent.com/loganmc10/mupen64plus-core/e5dbc4d81e5dfa44dad14699126fadc61a8e95cb/data/mupen64plus.ini)

That should fix the speed in DK's Parkway on the E version of the ROM.

**Comment by loganmc10** [comment] 2017-05-17 19:55
Ok so I did some testing on this:

I tested x64 and x86 (new dynarec) on Windows. I tested 2 full races (3 laps each) on each. So I tested 4 full races/12 laps. I tested 2 player mode (2nd player was no one, so they just sat there). I tested the U rom.

I couldn't reproduce this issue, I got every item I could, and it worked every time.

@hoderer are you sure you experienced this on a U rom? I can probably test an E rom in a bit to see if I can reproduce it there with the cheat on.

My only other thought: perhaps the ARM Dynarec is having an issue with this cheat. Since everyone who is reporting this is either on a Raspberry Pi or Android. You could try using the Cached Interpreter instead of the Dynarec and see if that solves the problem.

**Comment by audetto** [comment] 2017-05-17 21:09
I had this issue on Fedora 25 running on a 64 bit machine with an E rom.

**Comment by MorganCreek** [comment] 2017-05-17 21:35
@loganmc10:

The problem seems to appear more often with player 2, but I have no hard facts. I can quite reliably reproduce the bug with an E rom. My method is to almost finish a race with player 1, stop before the finish line and switch to player 2.

**Comment by loganmc10** [comment] 2017-05-17 21:37
I'm not so concerned about the E rom, since this cheat shouldn't have been applied to the E or J rom, I've submitted a PR to remove it (https://github.com/mupen64plus/mupen64plus-core/pull/280)

I'm really curious if anyone can reproduce this with the U rom, or with the E rom with the cheat in question removed.

**Comment by hoderer** [comment] 2017-05-17 23:04
@loganmc10: You were right. I just played two whole GPs (first two) with a friend (cheats/speed fixes on, Rom-Version "Mario Kart (U) [!]") and the item-bug did NOT appear once. I'm a bit confused, because I could swear that it happened a few months ago, but my test shows that I might be wrong... Maybe I've used my Sony Z5C (Snapdragon 810) instead of my Sony Z1C (Snapdragon 800), but that shouldnt make any difference, too I guess. The main point is: It seems like that the U-Versions are ok and that's pretty sweet! :-)

**Comment by loganmc10** [comment] 2017-05-17 23:32
Well it makes sense, and it's the best case scenario. We were just applying an incorrect cheat to the E and J versions.

We'll remove the cheat for the E and J versions for now. Hopefully someone can figure out how to properly convert the cheat for those versions

**Comment by hoderer** [comment] 2017-05-17 23:41
I'll keep an eye on it and play a little more MK64 in the next few days, but I think it's pretty clear now. If I discover something strange, I'll be right back and tell you.

@loganmc10 Did you ever consider a mame-like information/known bugs-window at the start of a game (with "don't show again"), so that people know the game/specific version of the game they wanna play right now has issues? Maybe some kind of bug-database would be cool, but that's a pretty big change, I know. Just thinking loud...

BTW: Thanks for the help everybody! :-)

**Comment by loganmc10** [comment] 2017-05-17 23:50
It would be helpful, but it's unlikely that anyone would take the time to create it. Project64's RDB file (their ini file) has notes in it like that, but it's probably not extremely thorough.

I would love if there was some kind of a wiki or something that kept track of bugs. Unfortunately, mupen64plus seems to have a smaller user base than Project64 (or at least they have a more active user base, with people posting frequently on forums, etc...), so it's unlikely that the wiki would get updated very much.

Project64 has a small number of very active people that test games and make modifications to their RDB (ini) file with game specific tweaks to the settings. Just recently I found 2 games (Beetle Adventure Racing and Star Wars Ep I Racer) that benefited by modifying the CountPerOp setting in the ini file. If we had people doing testing like that, we could probably solve a decent amount of issues.

Anyway, there isn't a good database of bugs. There also isn't a lot of people with the skills/knowledge to fix some of these issues. For instance, I would love to fix All Star Baseball 2001, I've identified where the problem in the code is, but I have no idea how to fix it.

**Comment by hoderer** [comment] 2017-05-18 00:05
Thanks for the infos. I totally agree and understand what you mean!

Since I don't have any clue about programming, I guess the RDB (ini) data of project64 can't be easily "ported" to mupen64 and that it would take a different type of work...

If you want me to test something else, I would totally do it, but I doubt that I can help, since I'm more of a user than programmer.

BTW: "Beetle Adventure Racing" was a pretty cool discovery in emulation a few years ago. Great game - didn't it know when I had a N64 back in the days. It's probably the best advertising/promotion-game for the N64 ever released, since most of those games are... let's say... not really good ;-)

**Comment by loganmc10** [comment] 2017-05-18 00:08
> I guess the RDB (ini) data of project64 can't be easily "ported" to mupen64 and that it would take a different type of work...

It depends on the game. The 2 projects work a little different so you can't guarantee it'll work that same. It's better to identify a bug, then go and look at the Project64 RDB to see what they do, then try that setting to see if it fixes the issue, rather than copy every setting over.

**Comment by hoderer** [comment] 2017-05-18 00:18
Ok. At least it seems like that it COULD work, but needs testing... I thought it would be way more complicated, but sure, testing is still a lot of work and needs time. Let's hope the community will grow in the future.

Just saw that the android port of project64 is in an very early stage and can't compete with mupen64 for android at this point. Didn't know that there is a port at all.

**Comment by 42Swampy** [comment] 2017-06-04 15:00
I changed to the US rom (Mario Kart 64 (U) [!].z64).
I have tested it with my girlfriend and the item error seems to disappear.

**Comment by loganmc10** [comment] 2017-07-17 20:00
This should be fixed now, can probably be closed

**Closed** 2017-09-14 12:33 UTC
Labels: game specific

**Comment by uqs** [comment] 2021-12-02 09:04
I've encountered the same, but it's 100% reproducible and not random at all: whenever a player uses the lightning bolt, then all other (human) players can no longer use any items at all (not sure about NPCs). So yeah, obviously it never happens in single player (because NPCs never get the lightning??)

This is on a Europe rom indeed, will try to see if a US rom fixes it.

**Comment by Narann** [comment] 2021-12-02 09:46
I think that's the original behavior. You can't use your item when you're tiny because of a lightning bolt.

**Comment by uqs** [comment] 2021-12-02 09:52
Sure, but then it's stuck in that mode till the _end_ of the race, that's the bug. I could imagine that the timer countdown doesn't work properly, due to cycle differences in the emulator.

**Comment by uqs** [comment] 2021-12-04 11:55
I can confirm that this is indeed ROM specific. Using an US ROM, the stuck items after lightning no longer occurs, yay!
