### ISSUE TITLE
Tetris 64 (J) freezes on boot.

### ISSUE THREAD

**Issue by AmbientMalice** [mupen64plus/mupen64plus-core#512] opened 2018-01-09 23:31 UTC
Works on PJ64.
![tetris64-000](https://user-images.githubusercontent.com/10704701/34748594-0e1f04ba-f5e9-11e7-96fa-bafb2b7005f9.png)

**Comment by loganmc10** [comment] 2018-01-09 23:47
Interesting. I know the unique thing about this game is the use of the bio sensor.

I see a screenshot here: http://www.raphnet-tech.com/products/raphnetraw/index.php

Showing it working with mupen64plus. So either it used to work, or it only currently works with the raphnet plugin. I'll look into it more tomorrow

**Comment by loganmc10** [comment] 2018-01-10 17:03
So this is a regression, which appeared when we introduced the use of the SI_DMA_BUSY flag. It seems to be affected by the timing of the SI interrupt. Shortening the SI interrupt delay fixes this game. If I make the interrupt delay too short, Body Harvest won't boot, if I make it too long, this game won't boot.

I never found an "overlapping" value where both games worked. I'll need to investigate further.

**Comment by bsmiles32** [comment] 2018-01-10 19:08
Can confirm that commit d9523052c8400fb284bd40128c37636c8cb2fe1a "Add SI_STATUS_DMA_BUSY" broke Tetris 64.

**Comment by bsmiles32** [comment] 2018-01-10 22:17
Tetris can boot with a SiDmaDuration <=170 (RandomizeInterrupt=False). Given that the interrupt timing jitter is <64 when RandomInterrupt=True, I took a safe value of 100 to make sure it can boot even with this option enabled. And with RandomInterrupt=True we get to enjoy the random selection of screen transitions :)

**Comment by bsmiles32** [comment] 2018-01-18 07:22
PR #513 has been merged, closing this.
Please re-open if the issue persists.

**Closed by bsmiles32** 2018-01-18 07:22 UTC
