### ISSUE TITLE
Donkey Kong 64 - Bone Displacement

### ISSUE THREAD

**Issue by Isotarge** [mupen64plus/mupen64plus-core#145] opened 2015-11-30 18:30 UTC
I'm reporting this long standing issue on behalf of the DK64 RTA & TAS communities.

I have completed a thorough technical analysis of the symptoms [here](https://docs.google.com/document/d/15XNghhrc-thXJpbKzWWuHXl-NXdzcaDLEf7poFVruh8)
Savestates to reproduce the issue are available [here](https://www.mediafire.com/folder/x5u53bpu42cex/Bone_Displacement_States)

Let's squish this bug!

**Comment by Gillou68310** [comment] 2015-12-01 10:00
Wow if only every issues could be described that way!!!

As a fan of DK64 I totally have interest into fixing this issue, be sure that this is right on top of my TODO list. However I may not have time to look at it until next week.

Having a concrete example of the correct behaviour is definitely gonna help finding the root issue. Both situation can know be compared.

> My current theory as to why this fixes the problem is that it allows the loop processing the bone data for each object to completely finish before being interrupted

You might be right with this because reducing the cycle count per emulated instruction reduces the issue. I'll start with that.

**Comment by Gillou68310** [comment] 2015-12-01 15:41
Quick question, how can I find the pointer to the object data for DK's character in your savestate (st0)?
Here's the pointer list of currently loaded objects at 0x7FBFF0:

0x7FBFF0	803904e0
0x7FBFF4	80391030
0x7FBFF8	80397210
0x7FBFFC	803a5620
0x7FC000	803a9760
0x7FC004	803c4120
0x7FC008	803d8f20
0x7FC00C	803eb8c0
0x7FC010	803eba50
0x7FC014	803ebbe0
0x7FC018	803ebd70
0x7FC01C	803ebf20
0x7FC020	803ec0b0
0x7FC024	80419fe0
0x7FC028	8043cc00
0x7FC02C	804851e0

**Comment by Isotarge** [comment] 2015-12-01 15:46
Ah yes, I probably should have mentioned this somewhere. A pointer to the player object can always be found at 0x7FBB4C

**Comment by Gillou68310** [comment] 2015-12-01 15:48
Thanks I'll check this ;-)

**Comment by theballaam96** [comment] 2016-03-31 16:55
This issue seems to have died down a bit, and it'd be awesome if it were to be solved. Hopefully it can be picked up again :)

**Comment by Isotarge** [comment] 2016-09-15 04:22
I have been working on this a lot lately using BizHawk's memory r/w/x callbacks to figure out more about the loop that writes bone positions. This research led to a second hacky fix for this issue that I discovered today, it still writes to RDRAM so it's not ideal but at least it doesn't lose all audio this time. See the heading "Hacky Fix 2" in the document linked in the OP for more information.

**Comment by Gillou68310** [comment] 2016-09-23 15:21
Ok I made more tests on this and I think I understand what's happening here.

Like you said FPR are set to 64bit mode at the beginning of the function 0x806195d0 and set back to 32bit at the end of it. The problem is when the function gets interrupted and an exception handler is called (eg: compare interrupt), the exception handler is executed with FPR in 64bit mode.

If the exception handler doesn't set FPR to 64bit mode it should probably not be executed in that mode.

My guess is that on real hardware no exception handler is called during the execution of the function 0x806195d0 but as we are using a hack for the cycle count it could explain why it's happening on the emulator.

The solution I propose is, if FPR is currently in 64bit mode, every time an exception handler is called switch FPR back to 32bit mode and save the EPC to a global variable (eg: fpr64_EPC). So when returning from the exception handler (ERET) if the current EPC is equal to the fpr64_EPC we know that we have to switch back FPR to 64bit mode.

**Comment by Gillou68310** [comment] 2016-09-26 16:53
@richard42, @Isotarge I started working on this here https://github.com/Gillou68310/mupen64plus-core/commit/c7deb01a3e6623e8851def8af7474da40dca8164 if anyone is interested.

**Comment by Gillou68310** [comment] 2016-10-17 10:34
@richard42, @Isotarge The more I think about this the more I think we should use a game specific hack to fix this issue. My above idea works but it probably won't fix anything else so it's pretty much useless.
 
From my testing it seems like the bone displacement only occurs when jumping to the exception handler caused by a compare interrupt.  

So the idea is just to avoid jumping to the exception handler when a compare interrupt is triggered.
Here's the implementation:
https://github.com/Gillou68310/mupen64plus-core/commit/1cc487ca06fb9d746172a8540e236ffc752ed69f

This need to be tested to be sure it doesn't break anything else and it actually fixes the bone displacement in every situations.

**Comment by Isotarge** [comment] 2016-10-18 03:19
Thanks for your work @Gillou68310 it's nice to see someone as dedicated to this bug as myself and the rest of the DK64 RTA/TAS community.

In the long term, I think we should avoid game specific hacks. In saying that, I do understand that if emulation inaccuracies (count register, for example) prevent us from fixing the issue properly right now, a game specific hack is a decent stopgap until accuracy improves.

> My above idea works but it probably won't fix anything else so it's pretty much useless.

Does this mean that your first fix implementation is accurate to console behavior? If so, I feel it would be counter productive to throw away this accurate behavior and instead use a hack just because the accurate behavior doesn't fix anything else.

If the first fix is not accurate to console behavior then we have the task of picking between 3 game specific hacks.

**Comment by Gillou68310** [comment] 2016-10-18 09:07
The first idea was also a hack to fix emulation inaccuracies but I tried to make it not game specific. It probably doesn't cover every cases right now and from my testing it's not needed for other games that's why I think it's not really a good solution.

**Comment by Isotarge** [comment] 2016-10-18 09:15
I understand, thank you for clearing that up

**Comment by Gillou68310** [comment] 2016-10-18 09:16
;-)

**Comment by loganmc10** [comment] 2016-11-08 20:59
This might be off topic, but is there any known fix/workaround to some of the timing issues in DK64? For instance, in the intro, right after the rap, Donkey Kong climbs up the cliff and then almost immediately jumps in the water, but I believe he is supposed to grab onto the vines and swing across.

Playing with count_per_op modifies DK's path, but I can't get him to successfully grab the vines.

**Comment by Gillou68310** [comment] 2016-11-08 21:46
I'm afraid not, my hack doesn't fix it either.

**Comment by taisel** [comment] 2016-11-11 01:10
Is it possible this is the reason a certain dev story exists on dk64? Modified latencies by including the expansion?

http://www.nintendolife.com/news/2013/05/donkey_kong_64_required_expansion_pak_to_prevent_game_breaking_bug

**Comment by loganmc10** [comment] 2017-03-21 19:58
Any status on this? I noticed that PJ64 merged this:

https://github.com/project64/project64/pull/1285

Which seems to be a cheat code that is supposed to fix the "polygon tearing", I assume that is the same thing as "bone displacement"? I haven't given it a try yet.

**Comment by loganmc10** [comment] 2017-03-21 20:03
The codes from retroben for the other versions are here (taken from the PJ64 forum):

```
Big Edit: codes for my version of it right here! (was really easy to port thanks to a good 32bit value search)

Donkey Kong 64 (E)
806128E2 0000

Donkey Kong 64 (J)
806170A2 0000
```

**Comment by loganmc10** [comment] 2017-04-28 19:23
@Gillou68310 is there something I can do to assist in getting this merged? Does the compare interrupt hack just need to be tested? I assume your fix would be a better solution than the cheat codes

**Comment by Gillou68310** [comment] 2017-05-04 08:54
Since retroben's cheat code seems to produce the same result as my hack I think we better use a cheat code instead of polluting the core with a hack. If my hack is proved to fix any other games then it could be interesting to merge it.

**Comment by loganmc10** [comment] 2017-08-10 14:55
@Gillou68310 I've recently been investigating some graphical glitches in Factor5 games (Rogue Squadron, Indiana Jones, Battle for Naboo). At CountPerOp=2, they all have some weird flickering graphics, see below:

![28998361-185fbcb4-79e6-11e7-94f6-2b9fdeeab6c2](https://user-images.githubusercontent.com/848146/29176429-190830d0-7da9-11e7-9bab-1289473d5ca1.png)

Indiana Jones and Battle for Naboo also have part of the image randomly disappear at CountPerOp=2, the problem is almost 100% with CountPerOp=1, but still happens sometimes.

I tested your original fix (setting the FGR mode to 32bit during the exception). This fixes the problem in these games! The Compare Int hack does not fix the issue in the Factor5 games.

I think it's worth looking at that fix and implementing it in mupen64plus, there may be other games besides Donkey Kong and these Factor5 games that benefit.

I refactored your original commit to make it compatible with the current codebase here:

https://github.com/loganmc10/mupen64plus-core/commit/2f7afd46a9236016241980a42592b979c3d9c0af

Thoughts? I haven't tested it with the new dynarec yet.

**Comment by Isotarge** [comment] 2017-09-13 05:46
Project64 has made some progress here, their latest builds do not seem to suffer from bone displacement issues, even without the RDRAM patch in the RDB. The commit responsible for fixing this issue is possibly https://github.com/project64/project64/commit/c7f895737ab3abc257931c4f9a7d65890a037f02

**Closed** 2017-10-02 08:45 UTC
Labels: bug, game specific
