### ISSUE TITLE
Make a New Release?

### ISSUE THREAD

**Issue by VarNepvius** [mupen64plus/mupen64plus-core#973] opened 2022-09-16 21:52 UTC
It has been 7 years since 2.5, the latest proper release. In 2019, a [prerelease was made in preparation for version 2.6](https://github.com/mupen64plus/mupen64plus-core/releases/tag/2.5.9), but it seems, that release never happened.

As a result, it seems that most distributions (including at least [Arch Linux](https://archlinux.org/packages/community/x86_64/mupen64plus/), [Debian](https://packages.debian.org/source/unstable/mupen64plus) and [Homebrew](https://github.com/Homebrew/formulae.brew.sh/blob/1cfcb8d65ec784231d3de9f62122e509d08d1672/_data/formula/mupen64plus.json#L22)) still package version 2.5 from 2015. This seems to have not been a great problem thus far, but a recent version of SDL 2 (2.24?) changed the behaviour of an API that [leads to a crash in the emulator at startup](https://github.com/mupen64plus/mupen64plus-core/issues/969). While [this has been fixed in the master branch](https://github.com/mupen64plus/mupen64plus-core/pull/970) already, those distributions mentioned above, that rely on a released "stable" version still have it, and as they update the SDL version, more and more will be affected by the bug. From personal experience i can say, that at least the Arch package is currently broken.

While users can of course build their own working version from Git or the Nightly, i don't think many packagers would want to go this way. And while the distributions can certainly also integrate the patch for the bug in their builds of the older version, i think this is also not quite optimal.

In light of all this, i wanted ask: _How reasonable would a new release in the near future be?_

**Comment by richard42** [comment] 2022-09-17 04:44
No we are clearly long overdue for a new tag and release. That SDL problem is significant and needs to be addressed, so I will start working on this in the coming weeks.

**Comment by mdinslage** [comment] 2022-10-28 22:44
Hi, not to be annoying, but can you give a status update on the progress of the new release? 
Thank You.

**Comment by LinuxDonald** [comment] 2023-03-11 23:09
Give it an status update here?

**Comment by fpi1337** [comment] 2023-06-12 06:36
I don't think you'll get one. One thing I was wondering about is the question, if the freezes that can occur while playing Majora's Mask with DynaRec is fixed now? Mupen64-Plus-Next suffered from this issue as well but at some point @m4xw managed to fix this issue. I wonder if this was the case as well for "original" Mupen64Plus?

**Comment by m4xw** [comment] 2023-06-12 15:46
> I don't think you'll get one. One thing I was wondering about is the question, if the freezes that can occur while playing Majora's Mask with DynaRec is fixed now? Mupen64-Plus-Next suffered from this issue as well but at some point @m4xw managed to fix this issue. I wonder if this was the case as well for "original" Mupen64Plus?

Freeze in question was a issue with special int and that should be fixed upstream since quite a while unless you refer to a different issue

**Comment by fpi1337** [comment] 2023-06-12 16:50
> > I don't think you'll get one. One thing I was wondering about is the question, if the freezes that can occur while playing Majora's Mask with DynaRec is fixed now? Mupen64-Plus-Next suffered from this issue as well but at some point @m4xw managed to fix this issue. I wonder if this was the case as well for "original" Mupen64Plus?
> 
> Freeze in question was a issue with special int and that should be fixed upstream since quite a while unless you refer to a different issue

Yes, I probably refer to a different issue but wanted to point out this freeze because it would occur with the old binary release. The issue I was talking about was related to a random freeze which was somehow connected to the dynarec problem that caused some players (including me) getting stuck behind Odolwa's door. This issue was already resolved in your core at some point (however the issue on GitHub is still open).

I just wanted to be sure that this was also solved in Mupen64Plus, not only in Mupen64Plus-Next.

**Comment by Jj0YzL5nvJ** [comment] 2023-06-12 20:06
> I just wanted to be sure that this was also solved in Mupen64Plus, not only in Mupen64Plus-Next.

#871

**Comment by fpi1337** [comment] 2023-06-13 04:55
> > I just wanted to be sure that this was also solved in Mupen64Plus, not only in Mupen64Plus-Next.
> 
> #871

Thank you! :) This OoT freeze (it was the same issue with MM) has been fixed:

> > > Hi Guillou! That's huge!
> > > As you are the only one with authority on the new dynarec, I will let @loganmc10 test a little and confirm so I can merge this. :)
> > 
> > Its still a bit of a WIP, theres still a few opcodes to match with the interpreter ;) This fixes the oot freeze as well and many other issues. What i am specifically excited about is interpreting single instruction for debugging, heh. He did a good job, currently running regression testing with him on my fork and standalone to catch anything obvious, so please no hasty merges. The issues have been over a decade old, at this point a few more days dont matter^^
> 
>

**Comment by m4xw** [comment] 2023-06-13 09:41
> > > I just wanted to be sure that this was also solved in Mupen64Plus, not only in Mupen64Plus-Next.
> > 
> > 
> > #871
> 
> Thank you! :) This OoT freeze (it was the same issue with MM) has been fixed. m4xw mentioned this in your linked issue:
> 
> > > > Hi Guillou! That's huge!
> > > > As you are the only one with authority on the new dynarec, I will let @loganmc10 test a little and confirm so I can merge this. :)
> > > 
> > > 
> > > Its still a bit of a WIP, theres still a few opcodes to match with the interpreter ;) This fixes the oot freeze as well and many other issues. What i am specifically excited about is interpreting single instruction for debugging, heh. He did a good job, currently running regression testing with him on my fork and standalone to catch anything obvious, so please no hasty merges. The issues have been over a decade old, at this point a few more days dont matter^^
> 
> So I guess when building Mupen64Plus, I need to set the option to use the new dynarec to 1 (Ari64 experimental) right? Since these fixes seem to be resolved around the new one.

It wasnt a issue with MM afaik, but it was so annoying/hard to reproduce it mightve been

**Comment by chenrui333** [comment] 2023-08-05 16:32
Any new updates? Thanks! :)

**Comment by richard42** [comment] 2023-08-12 23:26
yeah it is still on my radar. I've started working with a RISC-V single board computer to get Mupen64Plus building and running there so maybe I'll do the tag and release once I get a very basic build running on this new architecture.

**Closed** 2024-07-15 03:30 UTC
