### ISSUE TITLE
Pokemon Puzzle League New Dynarec assert

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#304] opened 2017-05-31 01:56 UTC
```
mupen64plus: ../../src/device/r4300/new_dynarec/new_dynarec.c:3335: alu_assemble: Assertion `s2h>=0' failed.
```

**Comment by loganmc10** [comment] 2017-05-31 02:31
This was on a Raspberry Pi

**Comment by Gillou68310** [comment] 2017-06-02 08:41
@bsmiles32 could you also assign me to this issue? ;-)

**Comment by loganmc10** [comment] 2017-09-07 20:10
I just tested this on Android (arm) and x86 and couldn't reproduce it. I suppose it's possible that I was using a debug build on my Raspberry Pi, and that allowed the assert to be triggered, but I don't really use my Raspberry Pi anymore so I can't be sure. In any event, it seems to work fine in a release build

**Comment by Gillou68310** [comment] 2017-09-07 20:17
I worked on this issue yesterday and there is really a bug here, so this should stay open!

**Comment by loganmc10** [comment] 2017-09-07 20:18
Oh ok my bad, I guess an assert does get triggered, it must be arm specific then, I didn't run across it in x86 with asserts enabled

**Comment by Gillou68310** [comment] 2017-09-07 20:19
Yep it's arm specific ;-)

**Comment by Gillou68310** [comment] 2019-01-28 13:34
@fzurita @loganmc10 I can not reproduce this issue with latest master. Could you guys double check?

**Comment by fzurita** [comment] 2019-01-28 13:37
Yep, not crashing any more. Unintended bug fix?

**Comment by Gillou68310** [comment] 2019-01-28 13:37
lol yeah

**Comment by Gillou68310** [comment] 2019-01-28 13:42
ok closing this

**Closed by Gillou68310** 2019-01-28 13:42 UTC
Labels: game specific
