### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by JakobDev** [mupen64plus/mupen64plus-core#861] opened 2021-06-01 16:02 UTC
The latest Release is Version 2.5 which was released over 6 years ago. Released are used by Linux distributions to package Mupen64Plus. Because of that the Version that Linux distros ship are very old. It would be nice to have a new release.

**Comment by richard42** [comment] 2021-06-02 04:31
This is a duplicate of #353.
Yes, we are definitely past due.
We did release 2.5.9 in 2019 but even that was 2 years ago.
There hasn't been that much activity in the last few months so I'll get a new build done this summer.

**Closed by richard42** 2021-06-02 04:31 UTC

**Comment by JakobDev** [comment] 2021-06-02 11:40
I had seen that there is a release from 2019 but it's marked as Pre-release and not as stable so many distros ship the latest stable version from 2015. A new stable release in the near future would be great.

**Comment by m4xw** [comment] 2021-06-02 11:43
Most issues in the beta release are due to new_dynarec (decade old issues even).
Gillou is working actively on it still and we fixed a bunch of the most significant issues.
So @richard42 's summer should only being after Gillou wrapped this up ;)
