### ISSUE TITLE
Turok 3 freezes after intro

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#338] opened 2017-07-17 02:37 UTC
This is very reproducible with Android, I haven't tried interpreter or different RSP.

Edit: It still locks up with CXD4 RSP, but using cached interpreter doesn't lock up. So it sounds like an issue with the new dynarec. Not sure if it's ARM specific.

**Comment by loganmc10** [comment] 2017-07-17 03:45
Yeah seems ok to me on my laptop, I'll test the x86 new dynarec tomorrow.

**Comment by loganmc10** [comment] 2017-07-17 19:02
Yeah it froze when I tested with the x86 new dynarec, but like I mentioned, no issues with the x64 dynarec, so it seems to be something wrong with the new dynarec, arm and x86

**Comment by fzurita** [comment] 2017-08-20 00:37
Hmm, I can't reproduce this issue any more. It looks like something fixed it. Can you verify @loganmc10 ?

**Comment by loganmc10** [comment] 2017-08-21 14:37
Still locked up for me using the x86 new dynarec right here:

![t](https://user-images.githubusercontent.com/848146/29524003-f85d7b8c-864b-11e7-8990-7348dd7d5fdd.png)

**Comment by fzurita** [comment] 2017-08-21 14:40
Hmmm, interesting, it did get further though.

**Comment by Gillou68310** [comment] 2019-01-28 13:51
@fzurita is this still reproductible?

**Comment by fzurita** [comment] 2019-01-28 14:58
I couldn't get it to freeze, but I couldn't get it to freeze any more before either. I would have @loganmc10 check the x86 new dynarec to make sure.

**Comment by Gillou68310** [comment] 2019-01-28 15:57
I'm not able to reproduce it on x86 new dynarec either. I'll close this ticket, it can be reopened if someone manage to reproduce it.

**Closed by Gillou68310** 2019-01-28 15:57 UTC
Labels: game specific
